storytime
storyai/infra pull request #2
Opened 2021-06-11 17:40 UTC by Arinono

wip

2021-06-14 14:36 UTC, Arinono commented on storytime/vm.tf
> +    image = "docker.io/storyscript/storytime"
**Heads up**

The current, deployed, instance for `jem` environment is using an image under `docker.io/arinono/storytime`.

2021-06-14 14:36 UTC, Arinono commented on storytime/ssl.tf
> +  name = "${var.app_environment}.runtime.storyscript-ci.com."
todo: use the variable

2021-06-14 14:52 UTC, williammartin requested changes

2021-06-14 14:52 UTC, williammartin commented on storytime/.terraform.lock.hcl
> +# This file is maintained automatically by "terraform init".
Shouldn't be committed

2021-06-14 14:52 UTC, williammartin commented on storytime/.gitignore
> +*.tfstate
Good, but let's make sure we're not using local tfstate anyway for Jem/other environments.

2021-06-14 14:52 UTC, williammartin commented on storytime/README.md
> +The script will install two Ubuntu instances with Apache web server located in private subnet, without public ip, inside an unmanaged instance group, with a load balancer using Terraform.
No longer correct.

2021-06-14 14:52 UTC, williammartin commented on storytime/variables-auth.tf
> +variable "app_project" {
Not sure "app" is really the right prefix here.

2021-06-14 14:54 UTC, williammartin commented
Please add an example of the command you need to run to deploy this to the README

2021-06-14 14:57 UTC, Arinono commented on storytime/.terraform.lock.hcl
> +# This file is maintained automatically by "terraform init".
Oh, good to know

2021-06-14 15:02 UTC, williammartin commented on storytime/vm.tf
> +    image = "docker.io/storyscript/storytime"
We should probably prioritise chores for:
 - Building from commit / master
 - Having a TF var here for the `tag` so we can deploy not only latest.

2021-06-14 15:47 UTC, JeanBarriere commented on storytime/ssl.tf
> +  certificate = file("/path/to/fullchain.pem")
**improvements**

maybe use `var.env_something` here?

2021-06-14 15:54 UTC, Arinono commented on storytime/ssl.tf
> +  certificate = file("/path/to/fullchain.pem")
a3e792d

2021-06-16 07:46 UTC, williammartin commented on storytime/.terraform.lock.hcl
> +# This file is maintained automatically by "terraform init".
I retracted this, it is important to have.

2021-06-16 07:46 UTC, williammartin commented on storytime/lb-unmanaged.tf
> +  path_matcher {
Did you ever figure out why we needed the path rules like this?

2021-06-16 07:48 UTC, Arinono commented on storytime/lb-unmanaged.tf
> +  path_matcher {
No, I just kept what was working :/

2021-06-16 07:49 UTC, williammartin commented on storytime/lb-unmanaged.tf
> +  path_matcher {
Do you think it is worth understanding?

2021-06-16 07:52 UTC, Arinono commented on storytime/lb-unmanaged.tf
> +  path_matcher {
I might be wrong, but I don't think so. Since, at some point, the way the runtime work is going to change. And if we end-up with only one web server (and deal with this properly on the code side), we won't even need path rules at all.

2021-06-16 07:53 UTC, williammartin commented on storytime/lb-unmanaged.tf
> +  path_matcher {
Sounds good to me.

2021-06-16 07:53 UTC, williammartin approved these changes

2021-06-16 09:42 UTC, Arinono commented
@williammartin 

I added the TFCloud config to hold the states there.
To be noted: it doesn't deal with applying stuff, only storing the states.

I updated the config and the readme accordingly (to explain how to switch workspaces).

Here is the TFCloud dashboard (to get an example)
![Screen Shot 2021-06-16 at 11 28 42](https://user-images.githubusercontent.com/10957531/122195157-629ffb00-ce96-11eb-8702-e76fa25536cb.png)
![Screen Shot 2021-06-16 at 11 29 46](https://user-images.githubusercontent.com/10957531/122195168-659aeb80-ce96-11eb-9804-49bdd2804271.png)

---

As you can see, I created an (empty) `codecov-ecm` workspace for later, but also for me to see how it's working with the CLI.
The first time I tried to `apply` after `init`, it asked me to pick a workspace to run the config on.
Later, I can switch with `terraform workspace select jem`

2021-06-16 10:41 UTC, merged